### ISSUE TITLE
Failure to read GRIB2 file with G2 from hpc-stack

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [NOAA-EMC/hpc-stack#212]
G2 (GRIB2 encoder/decoder) from hpc-stack is not reading grib2 files. Specifically, the routine getgb2 from G2, signaling that there is an error (code 96) in reading GRIB2 files. This is happening on all platforms(Jet/Hera/Orion/Wcoss-Cray/Wcoss-Dell).

I have an example(on Jet) that G2(not from hpc-stack, g2/v3.1.0) successfully decoding a GRIB2 file:
/lfs1/HFIP/hwrfv3/Biju.Thomas/Test_G2_getgb2/G2_getgb2
However, when I use G2(from hpc-stack, g2/3.4.1 ) to read the same file, it throws an error(error code 96).
/lfs1/HFIP/hwrfv3/Biju.Thomas/Test_G2_getgb2/G2_getgb2_hpc-stack

**Comment by kgerheiser** [comment]
What version of Jasper are you loading to create your executable? There was a bug in Jasper (version < 2.0.25) which affected g2.

**Comment by BijuThomas-NOAA** [comment]
Thanks.  I use jasper/2.0.22. I'll try 2.0.25 and report back

**Comment by edwardhartnett** [comment]
Can we change g2 CMake build to detect this problem?

**Comment by BijuThomas-NOAA** [comment]
Wondering if what version of jasper is being loaded for the G2 build?

**Comment by kgerheiser** [comment]
@edwardhartnett Yes, I believe that can be done by reading in the version.

`Wondering if what version of jasper is being loaded for the G2 build?`

I don't understand the question.

**Comment by kgerheiser** [comment]
The version of Jasper used at compile time doesn't matter because just the headers are used to fulfill compilation. It's not until the end user's executable is created that whatever version of the user has loaded Jasper is linked in, which is done through the package config file.

**Comment by edwardhartnett** [comment]
Not sure how that happens. Is this a shared library build?

Seems like the building application should be able to check the version from the jasper header?

**Comment by kgerheiser** [comment]
It's a static library. The building application doesn't check directly. It's brought in as a dependency of g2. When `find_package(g2)` is called CMake executes `g2-config.cmake` which runs `find_dependency(Jasper)`. So, you add the check in `PackageConfig.cmake.in` (which becomes `g2-config.cmake` when installed) so that any time g2 is used Jasper is checked.

**Comment by BijuThomas-NOAA** [comment]
> package config file

Thanks for the explanation. I thought since Jasper is static(libjasper.a), it is used in the compilation time of g2 in addition to the include files.

**Comment by kgerheiser** [comment]
The g2 library has no knowledge of the Jasper library aside from the necessary function declarations in the header. It is only at the end when an executable is created that the symbols are resolved from whatever `.a` is provided.

**Comment by BijuThomas-NOAA** [comment]
I have Cmake related issue to test G2 with jasper/2.0.25
Here are the modules I'm loading

module load cmake/3.16.1
module use /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/modulefiles/stack
module load hpc/1.1.0
module load hpc-intel/18.0.5.274
module load hpc-impi/2018.4.274

module load w3nco/2.4.1
module load sp/2.3.3
module load ip/3.3.3
module load bacio/2.4.1
module load **jasper/2.0.25**
module load g2/3.4.1

But the Cmake compilation uses jasper/2.0.22. Appreciate any help 
/apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort   -O2 -fp-model precise -i4 -r8 CMakeFiles/getgb2.x.dir/check_getgb2.f90.o  -o getgb2.x  /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/bacio/2.4.1/lib/libbacio_4.a /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/g2/3.4.1/lib/libg2_4.a /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/w3nco/2.4.1/lib/libw3nco_4.a /usr/lib64/libpng.so /usr/lib64/libz.so /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/jasper/**2.0.22**/lib64/libjasper.a /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/jpeg/9.1.0/lib/libjpeg.a -lirng -ldecimal -lcilkrts -lstdc++

**Comment by kgerheiser** [comment]
Did you start from a fresh build? CMake caches the location of libraries it has found and skips searching again.

**Comment by BijuThomas-NOAA** [comment]
I removed the build directory and started again. Still, CMake uses  jasper/2.0.22. Even if I do not load any jasper version it uses 2.0.22

**Comment by kgerheiser** [comment]
It must be picking it up from somewhere. It's not a default path. What are you building?

**Comment by BijuThomas-NOAA** [comment]
It is a simple Fortran code that calls getgb2 from G2

/mnt/lfs1/HFIP/hwrfv3/Biju.Thomas/Test_G2_getgb2/G2_getgb2_hpc-stack1/check_getgb2.f90

**Comment by kgerheiser** [comment]
Worked for me. Must be something in your environment. If I don't have Jasper loaded at all it picks up version 1.900.1 from `/usr/lib64` and when I load 2.0.25 it loads that.

```
cp -r /mnt/lfs1/HFIP/hwrfv3/Biju.Thomas/Test_G2_getgb2/G2_getgb2_hpc-stack1 ~
cd ~/G2_getgb2_hpc-stack1
module use modulefiles
module load build.jet.intel
module load jasper/2.0.25
rm -rf build
mkdir build && cd build
cmake ..
```

```
-- The C compiler identification is Intel 18.0.5.20180823
-- The Fortran compiler identification is Intel 18.0.5.20180823
...
-- Found bacio: /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/bacio/2.4.1/lib/libbacio_4.a (found version "2.4.0")
-- Found w3nco: /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/w3nco/2.4.1/lib/libw3nco_4.a (found version "2.4.0")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found PNG: /usr/lib64/libpng.so (found version "1.5.13")
-- Found g2: /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/g2/3.4.1/lib/libg2_4.a (found version "3.4.0")
-- Found JPEG: /usr/lib64/libjpeg.so (found version "62")
-- Found Jasper: /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/jasper/2.0.25/lib64/libjasper.a (found version "2.0.25")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Kyle.Gerheiser/G2_getgb2_hpc-stack1/build
```

**Comment by BijuThomas-NOAA** [comment]
I also see:
-- Found Jasper: /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/jasper/2.0.25/lib64/libjasper.a (found version "2.0.25") 
But later,
/apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/ifort   -O2 -fp-model precise -i4 -r8 CMakeFiles/getgb2.x.dir/check_getgb2.f90.o  -o getgb2.x  /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/bacio/2.4.1/lib/libbacio_4.a /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/g2/3.4.1/lib/libg2_4.a /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/w3nco/2.4.1/lib/libw3nco_4.a /usr/lib64/libpng.so /usr/lib64/libz.so /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/**jasper/2.0.22**/lib64/libjasper.a /lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/jpeg/9.1.0/lib/libjpeg.a -lirng -ldecimal -lcilkrts -lstdc++

**Comment by kgerheiser** [comment]
I found the problem.

In `g2-targets.cmake` (`/lfs4/HFIP/hfv3gfs/nwprod/hpc-stack/libs/intel-18.0.5.274/g2/3.4.1/lib/cmake/g2`)Jasper is hardcoded to the 2.0.22  path in `INTERFACE_LINK_LIBRARIES`. This should be an imported target without a path. This is because when you link Jasper using `${JASPER_LIBRARIES}` it's an absolute path and `FindJasper.cmake` doesn't provide an imported target (i.e. `Jasper::Jasper`).

**Comment by BijuThomas-NOAA** [comment]
Glad to hear that you found the problem. Is the same true for jpeg?.  Since Jasper/2.0.22 has a bug in it, how we can use Jasper/2.0.25 with CMake?

**Comment by BijuThomas-NOAA** [comment]
Any suggestion on how to use Jasper/2.0.25 during the G2 build using CMake on Jet?

**Comment by kgerheiser** [comment]
Yes, I will fix the path to point to the correct place. It was down for maintenance last time.

**Comment by kgerheiser** [comment]
I have fixed it on Jet and Orion. I checked Hera and it looks fine there.

**Comment by BijuThomas-NOAA** [comment]
Thanks.  The original issue still exists. The g2/3.4.1 with jasper/2.0.25 is not reading grib2 files. Specifically, the routine getgb2 from G2, signaling that there is an error (code 96) in reading GRIB2 files

On the other hand, g2/v3.1.0 with jasper/v1.900.1 reads grib2 files without any issues. 
I can provide a simple example if it helps.

**Comment by kgerheiser** [comment]
Yes, a reproducer would be helpful.

**Comment by BijuThomas-NOAA** [comment]
/lfs1/HFIP/hwrfv3/Biju.Thomas/Test_G2_getgb2/G2_getgb2_hpc-stack (The FORTRAN code check_getgb2.f90 reads a grib2 file using getgb2 routine from g2/3.4.1 with jasper/2.0.25 )
/lfs1/HFIP/hwrfv3/Biju.Thomas/Test_G2_getgb2/G2_getgb2 (Same but with g2/v3.1.0 loaded with jasper/v1.900.1)

There is compile.sh script for compilation and a script run_getgb2.sh to submit the jobs in each of those directories.
Thanks,

**Comment by BijuThomas-NOAA** [comment]
Wondering if have you had a chance to look at the issue to read GRIB2 files using G2 (getgb2 routine).

**Comment by kgerheiser** [comment]
I can reproduce this on my local machine. I will take a closer look.

**Comment by kgerheiser** [comment]
Good news, I believe I found the bug. It's an issue in g2, and unrelated to Jasper.

See here: https://github.com/NOAA-EMC/NCEPLIBS-g2/issues/49

**Comment by kgerheiser** [comment]
The output is now:



```
 hafs.trak.storm.2020082512.f00000 iunit_g =          201
 hafs.trak.storm.2020082512.f00000.ix iunit_i =          601
  firstval =   9.9990003E+20
  lastval =   9.9990003E+20
  fldmax =   9.9990003E+20
  fldmin =    11689.91
```

Which matches the correct output.

**Comment by kgerheiser** [comment]
The bug notwithstanding, If you change the file unit to be less than 100 (from 201). Your program should run.

**Comment by BijuThomas-NOAA** [comment]
Great! Much appreciated!

**Comment by kgerheiser** [comment]
The fixed g2 (v3.4.2) has been installed.
