### ISSUE TITLE
[INSTALL] MAPL/2.8.7

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/hpc-stack#348]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
MAPL

**What is the version/tag of the software?**
v 2.8.7

**What compilation options would you like set?**
use the current supported compilers for ufs-weather-model

**Which machines would you like to have the software installed?**
Please start with Orion and Hera

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by Hang-Lei-NOAA** [comment]
MAPL/2.8.7 has been installed on hera using the updated hpc-stack code with esmf/8_2_0_bs_14.
After loading hpc-stack libs:
-bash-4.2$ module load mapl/2.8.7-esmf-8_2_0_bs_14
-bash-4.2$ module show mapl/2.8.7-esmf-8_2_0_bs_14

   /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/mpi/intel/18.0.5.274/impi/2018.0.4/mapl/2.8.7-esmf-8_2_0_bs_14.lua:

help([[]])
conflict("mapl")
setenv("MAPL_ROOT","/scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/intel-18.0.5.274/impi-2018.0.4/mapl/2.8.7-esmf-8_2_0_bs_14")
whatis("Name: mapl")
whatis("Version: 2.8.7-esmf-8_2_0_bs_14")
whatis("Category: library")
whatis("Description: MAPL is a foundation layer of the GEOS architecture")

-bash-4.2$ ls $MAPL_ROOT
bin  etc  include  lib  lib64  share

**Comment by kgerheiser** [comment]
done on Orion

**Comment by rmontuoro** [comment]
A new release of MAPL ([2.9.0](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.9.0)) is available. It includes a few bug fixes and eliminates Python's dependency on Pandas, making it easier to install on NOAA computing platforms. This release supersedes 2.8.7 and it should be our current installation target.

Additional releases are planned within the next few days to potentially improve performance (2.10.0) and remove the `yaFyaml` dependency.

**Comment by kgerheiser** [comment]
Ok, will do @rmontuoro

**Comment by Hang-Lei-NOAA** [comment]
This (including v2.8.7 and v2.9.0) has been added on wcoss dell and hera

**Comment by kgerheiser** [comment]
MAPL 2.9.0 has been installed on Orion

**Comment by rmontuoro** [comment]
@kgerheiser - It looks like there's an extra `-debug` suffix in the ESMF prerequisites enforced in the following MAPL module files on Orion:
-`2.8.7-esmf-8_2_0_bs_14.lua`
-`2.9.0-esmf-8_2_0_bs_14.lua`
```
prereq_any("esmf/8_2_0_beta_snapshot_14-debug", "esmf/8_2_0_beta_snapshot_14-debug-debug")
```
Has MAPL been built using the ESMF debug version? If not, could you please remove the extra `-debug` at your earliest convenience? We are planning to use MAPL 2.9.0 in P7.2 experiments which are set to begin in the next couple of days.

**Comment by kgerheiser** [comment]
~~What is the issue? The module enforces the version of ESMF, but it can be regular _or_ debug. They are static libraries and the only dependence on ESMF is the build time interface which doesn't change between regular and debug.~~

Ah, I see, will fix.

**Comment by rmontuoro** [comment]
@kgerheiser - Thanks!

**Comment by kgerheiser** [comment]
Fixed

**Comment by rmontuoro** [comment]
Thank you!

**Comment by rmontuoro** [comment]
@kgerheiser - unfortunately the module does not work since it is pointing to the following MAPL install directory which does not exist:
```
/apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/impi-2018.4/mapl/2.9.0-esmf-8_2_0_bs_14
```

**Comment by kgerheiser** [comment]
Fixed

**Comment by climbfuji** [comment]
I built mapl 2.9.0 on Cheyenne with Intel 2021.2 and ESMF 8.2.0 bs14 (prod, not debug). I had to explicitly set the version in the config, because `build_stack.sh` didn't like the default module.

I could **not** build it with GNU (10.1.0) due to the following error:
```
/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-gnu-10.1.0/pkg/mapl-2.9.0/griddedio/GriddedIO.F90 -o CMakeFiles/MAPL.griddedio.dir/GriddedIO.F9
0.o
/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-gnu-10.1.0/pkg/mapl-2.9.0/generic/MAPL_Generic.F90:5453:42:

 5453 |           call MAPL_InternalStateRetrieve(meta%get_child_gridcomp(i), cmeta, RC=STATUS)
      |                                          1
Error: ‘get_child_gridcomp’ in variable definition context (actual argument to INTENT = OUT/INOUT) at (1) is not a variable
generic/CMakeFiles/MAPL.generic.dir/build.make:393: recipe for target 'generic/CMakeFiles/MAPL.generic.dir/MAPL_Generic.F90.o' failed
make[2]: *** [generic/CMakeFiles/MAPL.generic.dir/MAPL_Generic.F90.o] Error 1
make[2]: Leaving directory '/glade/p/ral/jntp/GMTB/tools/hpc-stack-v1.2.0/src/hpc-stack-gnu-10.1.0/pkg/mapl-2.9.0/build'
CMakeFiles/Makefile2:1733: recipe for target 'generic/CMakeFiles/MAPL.generic.dir/all' failed
make[1]: *** [generic/CMakeFiles/MAPL.generic.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by Hang-Lei-NOAA** [comment]
I have the same issue with GNU 9.2.0 on hera to build MAPL/2.9.0.
Other versions are fine with GNU.
Was trying to change the compiler flag, but still cannot over.

**Comment by rmontuoro** [comment]
Thank you, @climbfuji and @Hang-Lei-NOAA. I've created an [issue](https://github.com/GEOS-ESM/MAPL/issues/1141) on the NASA repository describing this problem.

**Comment by rmontuoro** [comment]
@climbfuji, @Hang-Lei-NOAA - This problem was recently fixed in MAPL (see PR [#1113](https://github.com/GEOS-ESM/MAPL/pull/1113)) Could you please try building the current `HEAD` of `develop`? If it works, NASA will issue a new release including this bugfix.

**Comment by Hang-Lei-NOAA** [comment]
Hi, Raffaele,
The develop branch works without any issue with gnu.

**Comment by climbfuji** [comment]
I can also build the head of develop with GNU 10.1.0 on Cheyenne.

**Comment by kgerheiser** [comment]
Think we've got MAPL 2.11.0 on all machines.

**Comment by rmontuoro** [comment]
@kgerheiser - Could you please point me to the location of the hpc-stack libraries (including MAPL) on WCOSS2?

**Comment by Hang-Lei-NOAA** [comment]
hpc-stack by EMC is only on Acorn:
/lfs/h1/emc/nceplibs/noscrub/hpc-stack/libs/hpc-stack
NCO install on other wcoss2 machines

**Comment by rmontuoro** [comment]
Thanks, @Hang-Lei-NOAA
